"""initial schema

Revision ID: 4587acf57f46
Revises: 
Create Date: 2026-07-02 10:51:22.629509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4587acf57f46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('languages',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('native_name', sa.String(length=120), nullable=True),
    sa.Column('tts_lang', sa.String(length=20), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code')
    )
    op.create_index(op.f('ix_languages_user_id'), 'languages', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('auto_speak_on_card_open', sa.Boolean(), nullable=False),
    sa.Column('speak_example', sa.Boolean(), nullable=False),
    sa.Column('speech_rate', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('speech_volume', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('import_batches',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_user_id'), 'import_batches', ['user_id'], unique=False)
    op.create_table('language_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('vocabulary_ratio', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('sentence_ratio', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('new_ratio', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('review_ratio', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('times_limit', sa.Integer(), nullable=False),
    sa.Column('sentence_times_limit', sa.Integer(), nullable=False),
    sa.Column('review_intervals', sa.JSON().with_variant(postgresql.ARRAY(sa.Integer()), 'postgresql'), nullable=False),
    sa.Column('sentence_review_intervals', sa.JSON().with_variant(postgresql.ARRAY(sa.Integer()), 'postgresql'), nullable=False),
    sa.Column('difficulty_filter', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sentence_difficulty_filter', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=False),
    sa.Column('topic_filter', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=False),
    sa.Column('situation_filter', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=False),
    sa.Column('frequency_filter', sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), 'postgresql'), nullable=False),
    sa.Column('include_passed_items', sa.Boolean(), nullable=False),
    sa.Column('passed_review_after_days', sa.Integer(), nullable=False),
    sa.Column('reset_on_fail', sa.Boolean(), nullable=False),
    sa.Column('avoid_same_day_repeat', sa.Boolean(), nullable=False),
    sa.Column('sort_mode', sa.String(length=30), nullable=False),
    sa.Column('item_ordering', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_id')
    )
    op.create_index(op.f('ix_language_settings_user_id'), 'language_settings', ['user_id'], unique=False)
    op.create_table('study_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pronunciation', sa.Text(), nullable=True),
    sa.Column('vietnamese_meaning', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('example_vietnamese', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('situation', sa.String(length=120), nullable=True),
    sa.Column('difficulty', sa.String(length=40), nullable=True),
    sa.Column('frequency_level', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('last_date_review', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('times_review', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('last_result', sa.String(length=20), nullable=True),
    sa.Column('hard_level', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("item_type in ('VOCABULARY', 'SENTENCE')", name='ck_item_type'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_study_items_archived', 'study_items', ['user_id', 'is_archived'], unique=False)
    op.create_index('idx_study_items_due', 'study_items', ['user_id', 'language_id', 'next_review_date', 'passed'], unique=False)
    op.create_index('idx_study_items_hard', 'study_items', ['user_id', 'hard_level'], unique=False)
    op.create_index('idx_study_items_type', 'study_items', ['user_id', 'language_id', 'item_type'], unique=False)
    op.create_index('idx_study_items_user_language', 'study_items', ['user_id', 'language_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=True),
    sa.Column('session_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_table('review_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('study_item_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('old_times_review', sa.Integer(), nullable=True),
    sa.Column('new_times_review', sa.Integer(), nullable=True),
    sa.Column('old_passed', sa.Boolean(), nullable=True),
    sa.Column('new_passed', sa.Boolean(), nullable=True),
    sa.Column('old_wrong_count', sa.Integer(), nullable=True),
    sa.Column('new_wrong_count', sa.Integer(), nullable=True),
    sa.Column('old_hard_level', sa.String(length=30), nullable=True),
    sa.Column('new_hard_level', sa.String(length=30), nullable=True),
    sa.Column('old_next_review_date', sa.Date(), nullable=True),
    sa.Column('new_next_review_date', sa.Date(), nullable=True),
    sa.Column('self_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("result in ('PASS', 'FAIL', 'SKIP')", name='ck_review_result'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_item_id'], ['study_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_logs_item', 'review_logs', ['study_item_id', 'created_at'], unique=False)
    op.create_index('idx_review_logs_user_date', 'review_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_review_logs_user_language_date', 'review_logs', ['user_id', 'language_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_logs_study_date'), 'review_logs', ['study_date'], unique=False)
    op.create_table('study_session_items',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('study_item_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('planned_bucket', sa.String(length=40), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_item_id'], ['study_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'study_item_id')
    )
    op.create_index(op.f('ix_study_session_items_session_id'), 'study_session_items', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_session_items_session_id'), table_name='study_session_items')
    op.drop_table('study_session_items')
    op.drop_index(op.f('ix_review_logs_study_date'), table_name='review_logs')
    op.drop_index('idx_review_logs_user_language_date', table_name='review_logs')
    op.drop_index('idx_review_logs_user_date', table_name='review_logs')
    op.drop_index('idx_review_logs_item', table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index('idx_study_items_user_language', table_name='study_items')
    op.drop_index('idx_study_items_type', table_name='study_items')
    op.drop_index('idx_study_items_hard', table_name='study_items')
    op.drop_index('idx_study_items_due', table_name='study_items')
    op.drop_index('idx_study_items_archived', table_name='study_items')
    op.drop_table('study_items')
    op.drop_index(op.f('ix_language_settings_user_id'), table_name='language_settings')
    op.drop_table('language_settings')
    op.drop_index(op.f('ix_import_batches_user_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_languages_user_id'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
